### ISSUE TITLE
NATS Consume task unable to connect to the NATS server

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-nats#25]
### Expected Behavior

NATS Consume task should be able to consume from NATS topic.

### Actual Behaviour

NATS Consume task is unable to connect to the NATS server. Here is the error:

```
2024-03-25 20:18:10.557 Timeout or no response waiting for NATS JetStream server
2024-03-25 20:18:10.557 java.io.IOException: Timeout or no response waiting for NATS JetStream server
	at io.nats.client.impl.NatsJetStreamImpl.responseRequired(NatsJetStreamImpl.java:249)
	at io.nats.client.impl.NatsJetStreamImpl.makeRequestResponseRequired(NatsJetStreamImpl.java:233)
	at io.nats.client.impl.NatsJetStreamImpl._getStreamNames(NatsJetStreamImpl.java:170)
	at io.nats.client.impl.NatsJetStreamImpl.lookupStreamBySubject(NatsJetStreamImpl.java:224)
	at io.nats.client.impl.NatsJetStream.createSubscription(NatsJetStream.java:329)
	at io.nats.client.impl.NatsJetStream.subscribe(NatsJetStream.java:639)
	at io.kestra.plugin.nats.Consume.run(Consume.java:72)
	at io.kestra.plugin.nats.Consume.run(Consume.java:31)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:710)
```

On the contrary, the Produce task is working perfectly fine.

### Steps To Reproduce

1. Run the example flow by providing the correct values for url and topic.
2. The execution fails with an error.

### Environment Information

- Kestra Version: 0.15.5
- Plugin version: 0.15.5
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```yaml
id: nats-consume
namespace: dev
tasks:
  - id: "consume"
    type: "io.kestra.plugin.nats.Consume"
    url: nats://<host-ip>:4444
    subject: kestra.publish
    durableId: durableId1
    pollDuration: PT20S
```

**Comment by shrutimantri** [comment]
Trigger task is also not working, but not sure if its the same reason.

**Comment by MustafaMunir123** [comment]
![image](https://github.com/user-attachments/assets/2222f660-0c89-4f4b-91a3-3dff1bc9a56a)

@shrutimantri Are you sure that you are starting your nats-server with JetStream enabled ?
